/**
 * MoneyLens Demo Product Database
 * All products are FICTIONAL for demonstration purposes only.
 * Clearly labelled as demo data throughout the UI.
 */

const PRODUCTS = [
  {
    id: "aeon-savings",
    name: "AEON Bank Savings+",
    institution: "AEON Bank (Demo)",
    type: "digital_bank",
    typeLabel: "Digital Bank Savings",
    advertisedRate: 3.80,
    effectiveRate: 3.65,
    rateType: "promotional",
    rateConditions: [
      "Maintain minimum RM5,000 average balance",
      "Perform at least 5 debit transactions per month",
      "Salary credit of RM3,000+ required for full rate"
    ],
    capitalProtection: "protected",
    protectionScheme: "PIDM protected up to RM250,000",
    riskLevel: "very_low",
    volatility: 0,
    liquidity: 5, // 1-5 scale
    liquidityLabel: "Instant Access",
    lockInMonths: 0,
    earlyWithdrawalPenalty: false,
    minDeposit: 100,
    maintenanceFee: 0,
    fees: ["No monthly fee"],
    reliability: 78,
    appScore: 82,
    branchAccess: false,
    bestFor: ["Emergency Funds", "Flexible Option", "Beginners"],
    dataFreshness: "Verified recently",
    summary: "Competitive digital savings with strong liquidity but rate conditions apply.",
    whatCouldGoWrong: "If you miss salary credit or transaction conditions, rate drops to base ~2.5%.",
    suitableFor: "Users who already salary credit and spend regularly.",
    avoidIf: "You want a pure set-and-forget rate with no conditions."
  },
  {
    id: "touch-n-go",
    name: "Touch 'n Go Go+",
    institution: "TNG Digital (Demo)",
    type: "digital_bank",
    typeLabel: "Digital Bank Savings",
    advertisedRate: 3.50,
    effectiveRate: 3.50,
    rateType: "guaranteed",
    rateConditions: [],
    capitalProtection: "protected",
    protectionScheme: "PIDM protected up to RM250,000",
    riskLevel: "very_low",
    volatility: 0,
    liquidity: 5,
    liquidityLabel: "Instant Access",
    lockInMonths: 0,
    earlyWithdrawalPenalty: false,
    minDeposit: 0,
    maintenanceFee: 0,
    fees: ["No fees"],
    reliability: 88,
    appScore: 90,
    branchAccess: false,
    bestFor: ["Emergency Funds", "Best Flexible Option", "Beginners"],
    dataFreshness: "Verified recently",
    summary: "Simple, no-condition rate with excellent app experience and instant access.",
    whatCouldGoWrong: "Rate is not the highest available.",
    suitableFor: "Anyone wanting simplicity and full liquidity.",
    avoidIf: "You need the absolute maximum rate and can meet complex conditions."
  },
  {
    id: "maybank-fd",
    name: "Maybank Fixed Deposit 12M",
    institution: "Maybank (Demo)",
    type: "fd",
    typeLabel: "Fixed Deposit",
    advertisedRate: 3.35,
    effectiveRate: 3.35,
    rateType: "guaranteed",
    rateConditions: [],
    capitalProtection: "protected",
    protectionScheme: "PIDM protected up to RM250,000",
    riskLevel: "very_low",
    volatility: 0,
    liquidity: 1,
    liquidityLabel: "Locked 12 months",
    lockInMonths: 12,
    earlyWithdrawalPenalty: true,
    minDeposit: 1000,
    maintenanceFee: 0,
    fees: ["Early withdrawal penalty applies"],
    reliability: 95,
    appScore: 75,
    branchAccess: true,
    bestFor: ["Stability", "Best for Capital Protection"],
    dataFreshness: "Verified recently",
    summary: "Traditional bank FD with strong brand trust and guaranteed rate, but money is locked.",
    whatCouldGoWrong: "Need money early → significant interest penalty.",
    suitableFor: "Money you definitely won't need for 12 months.",
    avoidIf: "You may need emergency access."
  },
  {
    id: "affin-hwang-mmf",
    name: "Affin Hwang Money Market Fund",
    institution: "Affin Hwang AM (Demo)",
    type: "money_market",
    typeLabel: "Money Market Fund",
    advertisedRate: 3.90,
    effectiveRate: 3.70,
    rateType: "variable",
    rateConditions: ["Past performance is not indicative of future results"],
    capitalProtection: "partial",
    protectionScheme: "Not PIDM protected — unit trust risk",
    riskLevel: "low",
    volatility: 0.3,
    liquidity: 4,
    liquidityLabel: "T+1 to T+2",
    lockInMonths: 0,
    earlyWithdrawalPenalty: false,
    minDeposit: 1000,
    maintenanceFee: 0.15,
    fees: ["Annual management fee ~0.15-0.30%"],
    reliability: 82,
    appScore: 70,
    branchAccess: true,
    bestFor: ["Best Balanced Option", "Short-Term Savings"],
    dataFreshness: "Updated 3 days ago",
    summary: "Slightly higher expected return than pure deposits but not capital guaranteed.",
    whatCouldGoWrong: "NAV can fluctuate slightly. Not protected by PIDM.",
    suitableFor: "Users comfortable with very low market risk for better yield.",
    avoidIf: "You need 100% capital guarantee."
  },
  {
    id: "boost-bank",
    name: "Boost Bank Savings",
    institution: "Boost Bank (Demo)",
    type: "digital_bank",
    typeLabel: "Digital Bank Savings",
    advertisedRate: 4.20,
    effectiveRate: 3.40,
    rateType: "promotional",
    rateConditions: [
      "Maximum RM50,000 balance for promotional rate",
      "Must complete 8 transactions monthly",
      "Promotion ends in 4 months",
      "Base rate after promotion: ~2.8%"
    ],
    capitalProtection: "protected",
    protectionScheme: "PIDM protected up to RM250,000",
    riskLevel: "very_low",
    volatility: 0,
    liquidity: 5,
    liquidityLabel: "Instant Access",
    lockInMonths: 0,
    earlyWithdrawalPenalty: false,
    minDeposit: 0,
    maintenanceFee: 0,
    fees: ["No monthly fee"],
    reliability: 72,
    appScore: 78,
    branchAccess: false,
    bestFor: ["Maximum Return (short term)"],
    dataFreshness: "Verified recently",
    summary: "Highest headline rate, but heavily conditional and time-limited.",
    whatCouldGoWrong: "Miss conditions → rate collapses. Promotion ends soon.",
    suitableFor: "Users who can meet transaction requirements for a few months.",
    avoidIf: "You want a stable long-term rate."
  },
  {
    id: "public-bank-savings",
    name: "Public Bank PB Save",
    institution: "Public Bank (Demo)",
    type: "savings",
    typeLabel: "Savings Account",
    advertisedRate: 2.85,
    effectiveRate: 2.85,
    rateType: "guaranteed",
    rateConditions: [],
    capitalProtection: "protected",
    protectionScheme: "PIDM protected up to RM250,000",
    riskLevel: "very_low",
    volatility: 0,
    liquidity: 5,
    liquidityLabel: "Instant Access",
    lockInMonths: 0,
    earlyWithdrawalPenalty: false,
    minDeposit: 500,
    maintenanceFee: 0,
    fees: ["No fee if balance > RM500"],
    reliability: 96,
    appScore: 72,
    branchAccess: true,
    bestFor: ["Stability", "Best for Beginners"],
    dataFreshness: "Verified recently",
    summary: "Solid traditional bank savings. Lower rate, extremely high trust and branch access.",
    whatCouldGoWrong: "Opportunity cost — lower return than digital options.",
    suitableFor: "Users who value brand trust and physical branches.",
    avoidIf: "You prioritise maximum yield."
  },
  {
    id: "gxbank",
    name: "GXBank High Interest",
    institution: "GXBank (Demo)",
    type: "digital_bank",
    typeLabel: "Digital Bank Savings",
    advertisedRate: 3.70,
    effectiveRate: 3.55,
    rateType: "promotional",
    rateConditions: [
      "First RM100,000 at promotional rate",
      "Requires monthly spend of RM500 on GX card"
    ],
    capitalProtection: "protected",
    protectionScheme: "PIDM protected up to RM250,000",
    riskLevel: "very_low",
    volatility: 0,
    liquidity: 5,
    liquidityLabel: "Instant Access",
    lockInMonths: 0,
    earlyWithdrawalPenalty: false,
    minDeposit: 0,
    maintenanceFee: 0,
    fees: ["No fees"],
    reliability: 80,
    appScore: 85,
    branchAccess: false,
    bestFor: ["Best Balanced Option", "Short-Term Savings"],
    dataFreshness: "Verified recently",
    summary: "Strong all-rounder with reasonable conditions and good app.",
    whatCouldGoWrong: "Must maintain card spend to keep full rate.",
    suitableFor: "Users who already spend with a debit card.",
    avoidIf: "You prefer zero conditions."
  },
  {
    id: "cimb-fd",
    name: "CIMB Preferred FD 6M",
    institution: "CIMB Bank (Demo)",
    type: "fd",
    typeLabel: "Fixed Deposit",
    advertisedRate: 3.40,
    effectiveRate: 3.40,
    rateType: "guaranteed",
    rateConditions: [],
    capitalProtection: "protected",
    protectionScheme: "PIDM protected up to RM250,000",
    riskLevel: "very_low",
    volatility: 0,
    liquidity: 2,
    liquidityLabel: "Locked 6 months",
    lockInMonths: 6,
    earlyWithdrawalPenalty: true,
    minDeposit: 5000,
    maintenanceFee: 0,
    fees: ["Early break penalty"],
    reliability: 93,
    appScore: 78,
    branchAccess: true,
    bestFor: ["Short-Term Savings", "Stability"],
    dataFreshness: "Verified recently",
    summary: "Shorter lock-in than 12-month FDs with competitive guaranteed rate.",
    whatCouldGoWrong: "Still locked for 6 months.",
    suitableFor: "Money you can lock for half a year.",
    avoidIf: "You need full flexibility."
  }
];

// Default weights
const DEFAULT_WEIGHTS = {
  return: 0.30,
  risk: 0.30,
  liquidity: 0.20,
  fees: 0.10,
  reliability: 0.10
};

// Goal-based weight adjustments
const GOAL_WEIGHTS = {
  emergency:   { return: 0.15, risk: 0.35, liquidity: 0.35, fees: 0.05, reliability: 0.10 },
  house:       { return: 0.25, risk: 0.30, liquidity: 0.20, fees: 0.10, reliability: 0.15 },
  education:   { return: 0.30, risk: 0.30, liquidity: 0.15, fees: 0.10, reliability: 0.15 },
  retirement:  { return: 0.40, risk: 0.25, liquidity: 0.10, fees: 0.10, reliability: 0.15 },
  vacation:    { return: 0.25, risk: 0.25, liquidity: 0.30, fees: 0.10, reliability: 0.10 },
  general:     { return: 0.30, risk: 0.30, liquidity: 0.20, fees: 0.10, reliability: 0.10 },
  max_return:  { return: 0.50, risk: 0.15, liquidity: 0.15, fees: 0.10, reliability: 0.10 },
  stability:   { return: 0.15, risk: 0.40, liquidity: 0.20, fees: 0.10, reliability: 0.15 }
};
